### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [strategywizard/ExpeditionToAnswersRepository#1]
Hello, @strategywizard 

It's me, again...

My colleague, who is translating "Expedition to terror" , would like to translate the second part too. Can he start with "Expedition to answers" as soon as the first part becomes available in Spanish?

**Comment by strategywizard** [comment]
Of course!  That's awesome news!
I appreciate you and your colleague's interest in doing these translations! 

    On Monday, September 14, 2020, 05:10:32 PM CDT, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard

It's me, again...

My colleague, who is translating "Expedition to terror" , would like to translate the second part too. Can he start with "Expedition to answers" as soon as the first part becomes available in Spanish?

**Comment by vidimus** [comment]
EDIT: wrong place to post that message.

Translation is in progress now.

**Comment by vidimus** [comment]
Hello, @strategywizard 

The translation is finished and now it's testing time! I will contact you in a few days to send you the translation file.

**Comment by vidimus** [comment]
Hello, @strategywizard 

Translation is ready:
[Localization.Spanish.txt](https://github.com/strategywizard/ExpeditionToAnswersRepository/files/5364805/Localization.Spanish.txt)




SPOILERS ALERT!!++++++++++++++++++++++++++++++++++++++++
>
>
>
>
>
>
>
>
>
>

Btw, testing the scenario, I found that interacting with your friend at the University during the ritual, meanwhile the bad guys have been wiped out and showing him/her again the Star Calendar, it makes the event restart, with the monsters spawning, and same to the stars puzzle.

**Comment by strategywizard** [comment]
Thanks for catching that, Vidimus.
I modified the text, adding a sentence instructing to remove the applicable Person Token.  Of course, I also programmed it to remove the token from the board to keep that issue from occurring.
I just pushed this change to GitHub.  Do you want to update your translation to add that sentence to the conversation of each person token once you've given them the Star Calendar (assuming they are innocent)?
Strategywizard 

    On Monday, October 12, 2020, 06:27:03 AM CDT, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard

Translation is ready:
Localization.Spanish.txt

SPOILERS ALERT!!++++++++++++++++++++++++++++++++++++++++

Btw, testing the scenario, I found that interacting with your friend at the University during the ritual, meanwhile the bad guys have been wiped out and showing him/her again the Star Calendar, it makes the event restart, with the monsters spawning, and same to the stars puzzle.

**Comment by vidimus** [comment]
Hello, @strategywizard 

Four sentences have been corrected. Here's the new version:
[Localization.Spanish.txt](https://github.com/strategywizard/ExpeditionToAnswersRepository/files/5372602/Localization.Spanish.txt)

**Comment by strategywizard** [comment]
Vidimus,
For some reason I can't seem to copy or open the file.
Strategywizard

    On Tuesday, October 13, 2020, 11:03:24 AM CDT, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard

Four sentences have been corrected. Here's the new version:
Uploading Localization.Spanish.txt…

**Comment by vidimus** [comment]
@strategywizard 
That's very weird. I see the file. Nevertheless, here it's again:

[Localization.Spanish.txt](https://github.com/strategywizard/ExpeditionToAnswersRepository/files/5374292/Localization.Spanish.txt)

**Comment by strategywizard** [comment]
Thanks, Vidimus.
For whatever reason, this link worked.  Maybe my laptop was just being stubborn, lol.
I pushed the changes, so please let me know if there are any issues once the update hits Valkyrie.
Thanks to you and your friend for the translation!
Strategywizard
 

    On Tuesday, October 13, 2020, 04:32:45 PM CDT, vidimus <notifications@github.com> wrote:  
 
 


@strategywizard
That's very weird. I see the file. Nevertheless, here it's again:

Localization.Spanish.txt

**Comment by vidimus** [comment]
Hello, @strategywizard 

I've seen it and it looks fine. Thanks for uploading it so quickly.

**Comment by strategywizard** [comment]
> Hello, @strategywizard
> 
> I've seen it and it looks fine. Thanks for uploading it so quickly.

Hi Vidimus,

I made a text change to one of the events ("CustomInsanity") for the English version for clarity and consistency.  I'm assuming that it won't affect your translation, but in case you wanted to update the translation file I thought I should let you know.

**Comment by vidimus** [comment]
Hello, @strategywizard. Thanks for telling me. I will check it and I would send you a new translation if needed.

**Comment by vidimus** [comment]
Hello, @strategywizard I will left the file untouched at the moment. Just in case I need to correct the file if a big typo or a mistake is found. Thanks again for your time and dedication with the scenarios.

**Comment by strategywizard** [comment]
Vidimus,
I'm planning to add voice overs to the intro and endings of my scenarios.  If I do this, will it affect your translations?  If so, what do I need to do to keep from messing anything up?
Strategywizard

    On Sunday, October 25, 2020, 02:54:33 AM CDT, vidimus <notifications@github.com> wrote:  
 
 


Hello, @strategywizard I will left untouched the file at the moment. Just in case I need to correct the file if a big typo or a mistake is found. Thanks again for your time and dedication with the scenarios.

**Comment by vidimus** [comment]
> Vidimus, I'm planning to add voice overs to the intro and endings of my scenarios.  If I do this, will it affect your translations?  If so, what do I need to do to keep from messing anything up?

Hello. That sounds (of course) great! And no, it doesn't affect in anyway to the translation.

By the way, I'm still working with "Book a room for a murder", but currently I'm quite busy and I've little time to do something with the translation.
